/* Generated by wayland-scanner 1.14.0 */

#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

extern const struct wl_interface wl_surface_interface;

static const struct wl_interface *types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	&wl_surface_interface,
	NULL,
	NULL,
	NULL,
	&wl_surface_interface,
	NULL,
	&wl_surface_interface,
	NULL,
	NULL,
	&wl_surface_interface,
	&wl_surface_interface,
	NULL,
	NULL,
	&wl_surface_interface,
};

static const struct wl_message wayfire_shell_requests[] = {
	{ "add_background", "uoii", types + 4 },
	{ "add_panel", "uo", types + 8 },
	{ "configure_panel", "uoii", types + 10 },
	{ "reserve", "uuuu", types + 0 },
	{ "set_color_gamma", "uaaa", types + 0 },
	{ "output_fade_in_start", "u", types + 0 },
};

static const struct wl_message wayfire_shell_events[] = {
	{ "output_created", "uuu", types + 0 },
	{ "output_resized", "uuu", types + 0 },
	{ "output_destroyed", "u", types + 0 },
	{ "output_autohide_panels", "uu", types + 0 },
	{ "gamma_size", "uu", types + 0 },
};

WL_EXPORT const struct wl_interface wayfire_shell_interface = {
	"wayfire_shell", 1,
	6, wayfire_shell_requests,
	5, wayfire_shell_events,
};

static const struct wl_message wayfire_virtual_keyboard_requests[] = {
	{ "send_key_pressed", "u", types + 0 },
	{ "send_key_released", "u", types + 0 },
	{ "set_virtual_keyboard", "o", types + 14 },
	{ "configure_keyboard", "oii", types + 15 },
	{ "start_interactive_move", "o", types + 18 },
};

static const struct wl_message wayfire_virtual_keyboard_events[] = {
	{ "match_output_size", "uu", types + 0 },
	{ "show_virtual_keyboard", "", types + 0 },
};

WL_EXPORT const struct wl_interface wayfire_virtual_keyboard_interface = {
	"wayfire_virtual_keyboard", 1,
	5, wayfire_virtual_keyboard_requests,
	2, wayfire_virtual_keyboard_events,
};

